In [1]:
import numpy as np

arr1 = np.array([1,2,3])

print(arr1)

[1 2 3]


In [2]:
print(type(arr1))

<class 'numpy.ndarray'>


In [3]:
print(arr1.shape)

(3,)


In [4]:
print(arr1[0])

1


In [5]:
print(arr1[1])

2


In [6]:
print(arr1[2])

3


In [7]:
arr1[2]=5
arr1

array([1, 2, 5])

In [8]:
arr2 = np.array([[1,2,3],[3,4,5]])
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [9]:
arr2[0][2]   #line [1] of array indicates 0 (1,2,3) and line [2] indicates 1 (3,4,5)
             #so, here it means in line 0 the 2nd part which is 3

3

In [10]:
print(arr2.shape) #here its mean arry is 2 dimentional and each dimention contain 3 part

(2, 3)


In [11]:
arr2[1,2]

5

In [12]:
print(arr2.shape) #here its mean we have 2 rows and each rows has 3 element

(2, 3)


In [13]:
arr2[1,2]

5

In [14]:
arr2[1][-1] #here (5 is -1), (4 is -2) & (3 is -3)

5

In [15]:
arr2[1][-2]

4

                             CHAPTER 2

In [16]:
arrS = np.array(['China','India','USA','Mexico'])
arrS

array(['China', 'India', 'USA', 'Mexico'], dtype='<U6')

                            CHAPTER 3

In [17]:
arrR = np.arange(0,20,2) #here, it means starting from 0 upto 20 (divided by 2 set)
arrR

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

                             CHAPTER 4

In [18]:
arrL = np.linspace(0,10,20)  #here, it means starting from 0 upto 10 (divided by 20 set)
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

                            CHAPTER 5

In [19]:
arr = np.random.rand(10) #here it means any 10 random number from 0 to 1
arr

array([0.95455166, 0.46265791, 0.67537012, 0.4828728 , 0.61243157,
       0.13733207, 0.65977964, 0.91467208, 0.04576512, 0.7650546 ])

In [20]:
arr = np.random.rand(8,4) # here it means any random number between 0 to 1 (with 8 rows and 4 coloumn)
arr

array([[0.64905718, 0.11724321, 0.53495245, 0.8558705 ],
       [0.68727658, 0.35373408, 0.90082546, 0.74507776],
       [0.81353028, 0.06300526, 0.67913994, 0.85203348],
       [0.63897986, 0.32767795, 0.09568366, 0.18049806],
       [0.11189754, 0.48563515, 0.97254184, 0.0186776 ],
       [0.49419488, 0.81019382, 0.04934643, 0.78036255],
       [0.53801305, 0.56228947, 0.32256338, 0.603523  ],
       [0.54346046, 0.14146034, 0.23590132, 0.81367636]])

In [21]:
print(np.zeros(10))
print('/n')
print(np.zeros((2,3)))    #for creating mass of an images

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
print(np.ones((10,10,1)))  #for creating mass of an images

[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]]


In [23]:
print(np.ones((10,10)))  #for creating mass of an images

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [24]:
arr = [0,1,2,8]           #here arr 0,1,2,8 is repeated 3 times
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2 8 8 8]


In [25]:
print(np.tile(arr,3))     #here,the code of In[36] is just modified

[0 1 2 8 0 1 2 8 0 1 2 8]


In [26]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [28]:
arr = np.random.rand(5,5) #here it means any random no. netween 0 to 1(in 5 rows and 5 column)
arr

array([[0.15646581, 0.10310833, 0.9514508 , 0.90171313, 0.9385647 ],
       [0.71215629, 0.74449309, 0.17318881, 0.79185141, 0.64653971],
       [0.03631747, 0.34211835, 0.79339112, 0.74651069, 0.82991138],
       [0.73007857, 0.82842831, 0.12083808, 0.45431284, 0.91358917],
       [0.7484389 , 0.83426005, 0.01830063, 0.65583911, 0.28944508]])

In [29]:
np.diag(arr)

array([0.15646581, 0.74449309, 0.79339112, 0.45431284, 0.28944508])

In [30]:
arr.ndim   #this code is used to find dimention of arr (here, which is 2)

2

In [31]:
arr.size

25

In [32]:
arr.shape

(5, 5)

In [33]:
np.random.randint(-10,10,4) #when we are delealing with negative(-) number we should use .randint instead of rand

array([ 9,  1,  7, -8])

In [34]:
arr+10

array([[10.15646581, 10.10310833, 10.9514508 , 10.90171313, 10.9385647 ],
       [10.71215629, 10.74449309, 10.17318881, 10.79185141, 10.64653971],
       [10.03631747, 10.34211835, 10.79339112, 10.74651069, 10.82991138],
       [10.73007857, 10.82842831, 10.12083808, 10.45431284, 10.91358917],
       [10.7484389 , 10.83426005, 10.01830063, 10.65583911, 10.28944508]])

In [35]:
arr-10

array([[-9.84353419, -9.89689167, -9.0485492 , -9.09828687, -9.0614353 ],
       [-9.28784371, -9.25550691, -9.82681119, -9.20814859, -9.35346029],
       [-9.96368253, -9.65788165, -9.20660888, -9.25348931, -9.17008862],
       [-9.26992143, -9.17157169, -9.87916192, -9.54568716, -9.08641083],
       [-9.2515611 , -9.16573995, -9.98169937, -9.34416089, -9.71055492]])

In [36]:
arr*2

array([[0.31293161, 0.20621667, 1.9029016 , 1.80342627, 1.8771294 ],
       [1.42431258, 1.48898618, 0.34637763, 1.58370282, 1.29307942],
       [0.07263493, 0.68423669, 1.58678223, 1.49302139, 1.65982276],
       [1.46015714, 1.65685662, 0.24167616, 0.90862568, 1.82717833],
       [1.49687779, 1.66852009, 0.03660125, 1.31167821, 0.57889016]])

In [37]:
arr/2

array([[0.0782329 , 0.05155417, 0.4757254 , 0.45085657, 0.46928235],
       [0.35607815, 0.37224654, 0.08659441, 0.3959257 , 0.32326986],
       [0.01815873, 0.17105917, 0.39669556, 0.37325535, 0.41495569],
       [0.36503929, 0.41421415, 0.06041904, 0.22715642, 0.45679458],
       [0.37421945, 0.41713002, 0.00915031, 0.32791955, 0.14472254]])

In [38]:
np.exp(arr)   #exp means expedentional

array([[1.16937078, 1.1086115 , 2.58946372, 2.46382035, 2.55630971],
       [2.03838187, 2.10537393, 1.1890906 , 2.20747959, 1.90892396],
       [1.036985  , 1.40792691, 2.21088108, 2.10962603, 2.29311552],
       [2.07524366, 2.28971718, 1.12844218, 1.57509067, 2.4932552 ],
       [2.11369774, 2.30310923, 1.01846911, 1.92675859, 1.33568608]])

In [39]:
arr

array([[0.15646581, 0.10310833, 0.9514508 , 0.90171313, 0.9385647 ],
       [0.71215629, 0.74449309, 0.17318881, 0.79185141, 0.64653971],
       [0.03631747, 0.34211835, 0.79339112, 0.74651069, 0.82991138],
       [0.73007857, 0.82842831, 0.12083808, 0.45431284, 0.91358917],
       [0.7484389 , 0.83426005, 0.01830063, 0.65583911, 0.28944508]])

In [40]:
np.log(arr)

array([[-1.85491778, -2.27197506, -0.0497673 , -0.10345884, -0.06340349],
       [-0.33945788, -0.29505171, -1.75337287, -0.23338152, -0.43612066],
       [-3.31545651, -1.07259856, -0.23143897, -0.29234534, -0.18643635],
       [-0.31460312, -0.18822498, -2.11330379, -0.78896924, -0.0903743 ],
       [-0.28976571, -0.18121012, -4.00081994, -0.42183979, -1.23978971]])

In [41]:
np.log2(arr)

array([[-2.67608068, -3.27776715, -0.07179904, -0.14925956, -0.0914719 ],
       [-0.4897342 , -0.42566964, -2.52958234, -0.33669836, -0.62918911],
       [-4.78319266, -1.54743263, -0.33389585, -0.42176517, -0.2689708 ],
       [-0.45387636, -0.27155124, -3.0488529 , -1.13824201, -0.13038255],
       [-0.41804356, -0.26143094, -5.77196309, -0.60858617, -1.78863846]])

In [42]:
np.log10(arr)

array([[-0.80558055, -0.98670623, -0.02161367, -0.04493161, -0.02753578],
       [-0.14742468, -0.12813933, -0.76148016, -0.10135631, -0.18940479],
       [-1.43988447, -0.46582364, -0.10051267, -0.12696397, -0.08096828],
       [-0.1366304 , -0.08174507, -0.91779618, -0.34264499, -0.03924906],
       [-0.12584365, -0.07869855, -1.73753402, -0.18320269, -0.53843383]])

In [43]:
np.sin(arr)

array([[0.15582817, 0.10292573, 0.81425855, 0.78439066, 0.80671075],
       [0.6534675 , 0.6775991 , 0.17232433, 0.71165516, 0.60242811],
       [0.03630948, 0.33548342, 0.712736  , 0.67908153, 0.73787156],
       [0.66692818, 0.73686976, 0.12054422, 0.43884496, 0.79170149],
       [0.68049569, 0.74079967, 0.01829961, 0.60982448, 0.28542043]])

In [44]:
np.cos(arr)

array([[0.98778418, 0.99468904, 0.58050238, 0.62026711, 0.59094651],
       [0.75695457, 0.73543148, 0.98504027, 0.70252896, 0.79817315],
       [0.99934059, 0.94204611, 0.70143238, 0.73406286, 0.67494115],
       [0.745122  , 0.67603473, 0.99270796, 0.8985628 , 0.61090814],
       [0.73275209, 0.67172602, 0.99983255, 0.7925365 , 0.95840241]])

In [45]:
np.tan(arr)

array([[0.15775528, 0.10347529, 1.4026791 , 1.2646014 , 1.36511636],
       [0.86328497, 0.92136265, 0.17494141, 1.0129905 , 0.75475868],
       [0.03633344, 0.35612208, 1.01611506, 0.92509998, 1.09323836],
       [0.89505904, 1.08998804, 0.12142969, 0.48838541, 1.29594194],
       [0.92868475, 1.10283009, 0.01830267, 0.76945917, 0.29780855]])

In [46]:
arr

array([[0.15646581, 0.10310833, 0.9514508 , 0.90171313, 0.9385647 ],
       [0.71215629, 0.74449309, 0.17318881, 0.79185141, 0.64653971],
       [0.03631747, 0.34211835, 0.79339112, 0.74651069, 0.82991138],
       [0.73007857, 0.82842831, 0.12083808, 0.45431284, 0.91358917],
       [0.7484389 , 0.83426005, 0.01830063, 0.65583911, 0.28944508]])

In [47]:
np.sum(arr) #here it is showing sum of all the number

14.461311814096057

In [48]:
np.sum(arr,axis=0)  #here it is showing the sum of axis 0

array([2.38345703, 2.85240812, 2.05716944, 3.55022718, 3.61805004])

In [49]:
np.sum(arr,axis=1)      #here it is showing the sum of axis 0

array([3.05130277, 3.06822932, 2.748249  , 3.04724697, 2.54628376])

In [50]:
np.min(arr)  #here it is showing min value 

0.018300627240989797

In [51]:
np.min(arr,axis=0)   #here it is showing min value of 0 axis

array([0.03631747, 0.10310833, 0.01830063, 0.45431284, 0.28944508])

In [52]:
np.min(arr,axis=1)    #here it is showing min value of 1 axis

array([0.10310833, 0.17318881, 0.03631747, 0.12083808, 0.01830063])

In [53]:
np.mean(arr)   #it is calculating mean

0.5784524725638422

In [54]:
np.mean(arr,axis=0)

array([0.47669141, 0.57048162, 0.41143389, 0.71004544, 0.72361001])

In [55]:
 np.median(arr)   #it is calculating median

0.7300785715060915

In [56]:
np.median(arr,axis=0)

array([0.71215629, 0.74449309, 0.17318881, 0.74651069, 0.82991138])

In [57]:
np.std(arr)   #it is calculating standard deviation

0.3127210966155798

In [58]:
np.std(arr,axis=0)

array([0.31303965, 0.2956292 , 0.3829543 , 0.15039676, 0.24001525])

In [59]:
np.var(arr)   #it is calculating variance

0.09779448426845079

In [60]:
np.var(arr,axis=0)

array([0.09799382, 0.08739662, 0.146654  , 0.02261918, 0.05760732])

In [61]:
arr[1:,2:3]

array([[0.17318881],
       [0.79339112],
       [0.12083808],
       [0.01830063]])

In [62]:
arr[1:,2:3]

array([[0.17318881],
       [0.79339112],
       [0.12083808],
       [0.01830063]])

In [63]:
arr[1:,2:-1]

array([[0.17318881, 0.79185141],
       [0.79339112, 0.74651069],
       [0.12083808, 0.45431284],
       [0.01830063, 0.65583911]])

In [64]:
np.sort(arr,axis=1)

array([[0.10310833, 0.15646581, 0.90171313, 0.9385647 , 0.9514508 ],
       [0.17318881, 0.64653971, 0.71215629, 0.74449309, 0.79185141],
       [0.03631747, 0.34211835, 0.74651069, 0.79339112, 0.82991138],
       [0.12083808, 0.45431284, 0.73007857, 0.82842831, 0.91358917],
       [0.01830063, 0.28944508, 0.65583911, 0.7484389 , 0.83426005]])

In [65]:
np.sort(arr)

array([[0.10310833, 0.15646581, 0.90171313, 0.9385647 , 0.9514508 ],
       [0.17318881, 0.64653971, 0.71215629, 0.74449309, 0.79185141],
       [0.03631747, 0.34211835, 0.74651069, 0.79339112, 0.82991138],
       [0.12083808, 0.45431284, 0.73007857, 0.82842831, 0.91358917],
       [0.01830063, 0.28944508, 0.65583911, 0.7484389 , 0.83426005]])

In [66]:
arr

array([[0.15646581, 0.10310833, 0.9514508 , 0.90171313, 0.9385647 ],
       [0.71215629, 0.74449309, 0.17318881, 0.79185141, 0.64653971],
       [0.03631747, 0.34211835, 0.79339112, 0.74651069, 0.82991138],
       [0.73007857, 0.82842831, 0.12083808, 0.45431284, 0.91358917],
       [0.7484389 , 0.83426005, 0.01830063, 0.65583911, 0.28944508]])

In [67]:
arr.T

array([[0.15646581, 0.71215629, 0.03631747, 0.73007857, 0.7484389 ],
       [0.10310833, 0.74449309, 0.34211835, 0.82842831, 0.83426005],
       [0.9514508 , 0.17318881, 0.79339112, 0.12083808, 0.01830063],
       [0.90171313, 0.79185141, 0.74651069, 0.45431284, 0.65583911],
       [0.9385647 , 0.64653971, 0.82991138, 0.91358917, 0.28944508]])

In [68]:
arr[:3,:]

array([[0.15646581, 0.10310833, 0.9514508 , 0.90171313, 0.9385647 ],
       [0.71215629, 0.74449309, 0.17318881, 0.79185141, 0.64653971],
       [0.03631747, 0.34211835, 0.79339112, 0.74651069, 0.82991138]])

In [69]:
arr[:3,:].T   #T means transpose

array([[0.15646581, 0.71215629, 0.03631747],
       [0.10310833, 0.74449309, 0.34211835],
       [0.9514508 , 0.17318881, 0.79339112],
       [0.90171313, 0.79185141, 0.74651069],
       [0.9385647 , 0.64653971, 0.82991138]])

In [70]:
arr[:3,:].transpose()       #the answer is same as In[82]

array([[0.15646581, 0.71215629, 0.03631747],
       [0.10310833, 0.74449309, 0.34211835],
       [0.9514508 , 0.17318881, 0.79339112],
       [0.90171313, 0.79185141, 0.74651069],
       [0.9385647 , 0.64653971, 0.82991138]])

In [71]:
arr[:3,:].flatten()    #this command is to flatten the data

array([0.15646581, 0.10310833, 0.9514508 , 0.90171313, 0.9385647 ,
       0.71215629, 0.74449309, 0.17318881, 0.79185141, 0.64653971,
       0.03631747, 0.34211835, 0.79339112, 0.74651069, 0.82991138])

                            CHAPTER 6

In [72]:
arr = np.array([4,5,6,7,8])
arr

array([4, 5, 6, 7, 8])

In [73]:
arr1 = np.append(arr,8)
arr1

array([4, 5, 6, 7, 8, 8])

In [74]:
arr2 = np.insert(arr,0, [1,2,3])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
arr3 = np.insert(arr, -1, [1,2,3])
arr3

array([4, 5, 6, 7, 1, 2, 3, 8])

In [78]:
arr3 = np.delete(arr2,0)
arr3

array([2, 3, 4, 5, 6, 7, 8])

In [80]:
arr3 = np.delete(arr1,3)
arr3

array([4, 5, 6, 8, 8])

In [82]:
arrC = arr3.copy()
arrC

array([4, 5, 6, 8, 8])