In [1]:
import numpy as np

                                  Chapter 7

In [2]:
arr1 = np.array([[1,2,3,4],[1,2,3,4]])
arr2 = np.array([[5,6,7,8],[5,6,7,8]])
arr_cat = np.concatenate((arr1,arr2),axis=0)
print(arr_cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [3]:
arr1 = np.array([[1,2,3,4],[1,2,3,4]])
arr2 = np.array([[5,6,7,8],[5,6,7,8]])
arr_cat = np.concatenate((arr1,arr2),axis=1)
print(arr_cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [4]:
catV = np.vstack((arr1,arr2))   #it is as smilar as In[10]
catV 

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [5]:
cat = np.hstack((arr1,arr2))   #it is as smilar as In[11]
cat

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

                                  Chapter 8

In [6]:
arr = np.array([1,2,3,4,5,6,3,6,1,2,4])  #this fuction is used to find unique value and to remove the repetead value 
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [7]:
uniques,counts =np.unique(arr, return_counts=True)  #this function is used to find unique value as well as how many times this this value occurs
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 2 1 2]


                                  CHAPTER - 9

In [12]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
print(np.intersect1d(arr1, arr2))  #common on both arr1 and arr2
print(np.union1d(arr1, arr2))       #taken number which is common 
print(np.setdiff1d(arr1, arr2))          #whats in arry1 and not in arry2
print(np.setxor1d(arr1, arr2))       #here, the set of number which is not repeated

[3 4 5]
[1 2 3 4 5 6 7]
[1 2]
[1 2 6 7]
